name: Build, release and deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'package-lock.json'
      - '*.config.*'
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: "👷 Node.js build"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
    - name: Clean dist folder
      run: rm -rf dist
    - name: Use default npm registry
      run: rm package-lock.json && npm config set registry https://registry.npmjs.org/
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build

  deploy:
    name: "🚀 Deploy on production"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy on production
      uses: easingthemes/ssh-deploy@main
      with:
        SCRIPT_BEFORE: |
          echo "Déploiement sur le serveur distant"
          rm -rf /var/www/quentin-desbin/*
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
        SOURCE: './dist/'
        TARGET: '/var/www/quentindesbin'
        ARGS: '-avz --delete'
        EXCLUDE: ''
        SCRIPT_AFTER: |
          echo "Ajustement des permissions"
          sudo chown -R www-data:www-data /var/www/quentin-desbin

